// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHWTRMATVcsuJY6O2H6ETxVO5f2C3kfq8',
    appId: '1:1028470651947:web:379e8cf9beb976954b3e6e',
    messagingSenderId: '1028470651947',
    projectId: 'ship-1eb77',
    authDomain: 'ship-1eb77.firebaseapp.com',
    storageBucket: 'ship-1eb77.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCHuSaBxxzx1PGS26Jfg6bm0VTH8DUEXQ',
    appId: '1:1028470651947:android:cb92a04b7ed0bc954b3e6e',
    messagingSenderId: '1028470651947',
    projectId: 'ship-1eb77',
    storageBucket: 'ship-1eb77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB9Ur3pwUpwR0WBlbKtbbMztR1SgI8gCI',
    appId: '1:1028470651947:ios:bcf4531f3950e9f14b3e6e',
    messagingSenderId: '1028470651947',
    projectId: 'ship-1eb77',
    storageBucket: 'ship-1eb77.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB9Ur3pwUpwR0WBlbKtbbMztR1SgI8gCI',
    appId: '1:1028470651947:ios:bcf4531f3950e9f14b3e6e',
    messagingSenderId: '1028470651947',
    projectId: 'ship-1eb77',
    storageBucket: 'ship-1eb77.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHWTRMATVcsuJY6O2H6ETxVO5f2C3kfq8',
    appId: '1:1028470651947:web:efa47a6dcb0bc69a4b3e6e',
    messagingSenderId: '1028470651947',
    projectId: 'ship-1eb77',
    authDomain: 'ship-1eb77.firebaseapp.com',
    storageBucket: 'ship-1eb77.appspot.com',
  );
}
